"""
Markdown -> styled HTML -> PDF (via Edge headless).

Usage:
  python scripts/md_to_pdf.py <input.md> [output_basename]
"""
from __future__ import annotations

import os
import subprocess
import sys
import io
import time
from pathlib import Path

if sys.platform.startswith("win"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

try:
    import markdown  # type: ignore
except ImportError:
    print("Installing markdown...", flush=True)
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", "markdown"])
    import markdown  # type: ignore


CSS = r"""
@page { size: A4; margin: 18mm 16mm 18mm 16mm; }
* { box-sizing: border-box; }
html, body {
  font-family: "Hiragino Kaku Gothic ProN", "游ゴシック", "Yu Gothic UI", "Meiryo", system-ui, sans-serif;
  font-size: 10.5pt;
  line-height: 1.7;
  color: #1a1a1a;
  background: #f1f1f4;
}
body { margin: 0; padding: 18px; }
.sheet {
  max-width: 210mm;
  margin: 0 auto;
  background: white;
  padding: 18mm 16mm 22mm 16mm;
  box-shadow: 0 4px 20px rgba(0,0,0,0.08);
  border: 1px solid #e2e2e6;
}
h1 {
  font-size: 22pt;
  font-weight: 800;
  color: #142d52;
  border-bottom: 3px solid #2c4a7e;
  padding-bottom: 6px;
  margin: 0 0 12px 0;
}
h2 {
  font-size: 15pt;
  color: #1c3a66;
  border-left: 5px solid #2c4a7e;
  padding-left: 10px;
  margin-top: 22px;
  margin-bottom: 8px;
}
h3 {
  font-size: 12.5pt;
  color: #243d63;
  margin-top: 14px;
  margin-bottom: 4px;
}
p { margin: 4px 0 8px 0; }
ul, ol { margin: 4px 0 8px 0; padding-left: 24px; }
li { margin-bottom: 2px; }
hr { border: 0; border-top: 1px dashed #b7b7c0; margin: 16px 0; }
table {
  border-collapse: collapse;
  margin: 8px 0 12px 0;
  width: 100%;
  font-size: 10pt;
}
th, td {
  border: 1px solid #c5c9d2;
  padding: 5px 9px;
  vertical-align: top;
}
th {
  background: #2c4a7e;
  color: white;
  font-weight: 600;
  text-align: left;
}
tr:nth-child(even) td { background: #f7f8fb; }
code {
  background: #f1f1f4;
  padding: 1px 5px;
  border-radius: 3px;
  font-family: "Cascadia Code", "Consolas", "Menlo", monospace;
  font-size: 9.5pt;
  color: #c0392b;
}
pre {
  background: #1c1c20;
  color: #e8e8ec;
  padding: 12px 14px;
  border-radius: 6px;
  font-family: "Cascadia Code", "Consolas", "Menlo", monospace;
  font-size: 9pt;
  line-height: 1.55;
  overflow-x: auto;
  margin: 6px 0 12px 0;
}
pre code { background: transparent; color: inherit; padding: 0; }
blockquote {
  border-left: 4px solid #2c4a7e;
  background: #f0f4fb;
  padding: 8px 14px;
  margin: 6px 0 12px 0;
  color: #1c2e50;
  font-style: italic;
}
strong { color: #142d52; }
a { color: #2c4a7e; text-decoration: none; border-bottom: 1px dotted #2c4a7e; }
.header-meta {
  background: linear-gradient(135deg, #2c4a7e 0%, #4a6fa8 100%);
  color: white;
  padding: 8px 14px;
  border-radius: 6px;
  font-size: 10pt;
  margin-bottom: 14px;
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 12px;
}
.header-meta strong { color: white; }
.footer-note {
  text-align: center;
  color: #888;
  font-size: 9pt;
  margin-top: 24px;
  font-style: italic;
}
"""


def render(md_path: Path, out_basename: str | None = None) -> tuple[Path, Path | None]:
    md_text = md_path.read_text(encoding="utf-8")

    # Strip YAML frontmatter if present
    if md_text.startswith("---"):
        end = md_text.find("\n---", 4)
        if end != -1:
            md_text = md_text[end + 4 :].lstrip()

    html_body = markdown.markdown(
        md_text,
        extensions=["extra", "tables", "fenced_code", "sane_lists", "toc"],
    )

    html = f"""<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8" />
<title>{md_path.stem}</title>
<style>{CSS}</style>
</head>
<body>
<div class="sheet">
{html_body}
<div class="footer-note">— Generated by LegalShield Document Pipeline / {md_path.name} —</div>
</div>
</body>
</html>
"""

    base = out_basename or md_path.stem
    html_path = md_path.parent / f"{base}.html"
    pdf_path = md_path.parent / f"{base}.pdf"
    html_path.write_text(html, encoding="utf-8")
    print(f"[html] {html_path}")

    edge_candidates = [
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    ]
    edge = next((c for c in edge_candidates if os.path.exists(c)), None)
    if not edge:
        print("[warn] Edge not found; PDF skipped.")
        return html_path, None

    subprocess.run(
        [edge, "--headless", "--disable-gpu",
         f"--print-to-pdf={pdf_path}",
         f"file:///{html_path.as_posix()}"],
        check=True, capture_output=True,
    )
    for _ in range(20):
        if pdf_path.exists() and pdf_path.stat().st_size > 0:
            break
        time.sleep(0.25)
    if pdf_path.exists():
        print(f"[pdf ] {pdf_path}  ({pdf_path.stat().st_size:,} bytes)")
    else:
        print(f"[warn] PDF not generated at {pdf_path}")
        pdf_path = None
    return html_path, pdf_path


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python scripts/md_to_pdf.py <input.md> [output_basename]")
        sys.exit(1)
    md = Path(sys.argv[1]).resolve()
    if not md.exists():
        print(f"ERROR: {md} not found")
        sys.exit(1)
    out = sys.argv[2] if len(sys.argv) > 2 else None
    html_path, pdf_path = render(md, out)

    if sys.platform.startswith("win"):
        if pdf_path:
            os.startfile(str(pdf_path))  # noqa
            print(f"[open] PDF opened")
        else:
            os.startfile(str(html_path))  # noqa
            print(f"[open] HTML opened (PDF unavailable)")


if __name__ == "__main__":
    main()
