"""
Reference manifest: 公開資料・論文・法規・社会調査の URL 一覧。

各エントリ:
  key:        ユニーク ID (BibTeX cite-key にも使う)
  title:      日本語/中国語/英語タイトル
  publisher:  出典機関
  url:        ダウンロード URL
  kind:       'pdf' | 'html' | 'xlsx' | 'csv' | 'zip'
  category:   'jp' | 'tw' | 'academic' | 'international' | 'laws'
  subcategory: フォルダ細分
  year:       公開年
  necessity_for: ['product' | 'research' | 'governance' | 'policy'] のリスト
  bibtex_type: 'misc' | 'article' | 'techreport' | 'inproceedings' | 'manual'
  notes:      備考 (ペイウォール、要登録、推測URL等)
"""
from __future__ import annotations

REFS = [
    # ========================================================================
    # 🇯🇵 日本政府統計・調査
    # ========================================================================
    {
        "key": "npa_stalker_dv_r5",
        "title": "令和5年におけるストーカー事案、配偶者からの暴力事案等",
        "publisher": "警察庁",
        "url": "https://www.npa.go.jp/bureau/safetylife/stalker/R5_STDVRPCAkouhousiryou_syuusei.pdf",
        "kind": "pdf",
        "category": "jp",
        "subcategory": "npa",
        "year": 2024,
        "necessity_for": ["product", "research", "policy"],
        "bibtex_type": "techreport",
        "notes": "ギャップ係数 18.36 の根拠。npa_stalking.py で取得済",
    },
    {
        "key": "npa_stalker_dv_r4",
        "title": "令和4年におけるストーカー事案、配偶者からの暴力事案等",
        "publisher": "警察庁",
        "url": "https://web.archive.org/web/20230928204858/https://www.npa.go.jp/bureau/safetylife/stalker/R4_STDVRPCAkouhousiryou.pdf",
        "original_url": "https://www.npa.go.jp/bureau/safetylife/stalker/R4_STDVRPCAkouhousiryou.pdf",
        "via": "wayback_machine",
        "kind": "pdf",
        "category": "jp",
        "subcategory": "npa",
        "year": 2023,
        "necessity_for": ["research"],
        "bibtex_type": "techreport",
    },
    {
        "key": "npa_stalker_dv_r3",
        "title": "令和3年におけるストーカー事案、配偶者からの暴力事案等",
        "publisher": "警察庁",
        "url": "https://web.archive.org/web/2023/https://www.npa.go.jp/bureau/safetylife/stalker/R3_STDVRPCAkouhousiryou.pdf",
        "original_url": "https://www.npa.go.jp/bureau/safetylife/stalker/R3_STDVRPCAkouhousiryou.pdf",
        "via": "wayback_machine",
        "kind": "pdf",
        "category": "jp",
        "subcategory": "npa",
        "year": 2022,
        "necessity_for": ["research"],
        "bibtex_type": "techreport",
    },
    {
        "key": "npa_crime_situation_r5",
        "title": "令和5年の犯罪情勢",
        "publisher": "警察庁",
        "url": "https://www.npa.go.jp/publications/statistics/crime/situation/r5_report.pdf",
        "kind": "pdf",
        "category": "jp",
        "subcategory": "npa",
        "year": 2024,
        "necessity_for": ["product", "research"],
        "bibtex_type": "techreport",
        "notes": "ストーカー検挙 1,081 件等の根拠",
    },
    {
        "key": "cao_dv_h29_summary",
        "title": "男女間における暴力に関する調査 (平成29年度) 概要",
        "publisher": "内閣府男女共同参画局",
        "url": "https://www.gender.go.jp/policy/no_violence/e-vaw/chousa/pdf/h29danjokan-gaiyo.pdf",
        "kind": "pdf",
        "category": "jp",
        "subcategory": "cao",
        "year": 2018,
        "necessity_for": ["product", "research", "policy"],
        "bibtex_type": "techreport",
        "notes": "「恥ずかしくてだれにも言えなかった」女性の半数の根拠",
    },
    {
        "key": "cao_dv_r2_landing",
        "title": "男女間における暴力に関する調査 (令和2年度) ランディング",
        "publisher": "内閣府男女共同参画局",
        "url": "https://www.gender.go.jp/policy/no_violence/e-vaw/chousa/r02_boryoku_cyousa.html",
        "kind": "html",
        "category": "jp",
        "subcategory": "cao",
        "year": 2021,
        "necessity_for": ["research"],
        "bibtex_type": "misc",
        "notes": "PDF へのリンクはこの HTML から抽出",
    },
    {
        "key": "cao_dv_r5_landing",
        "title": "男女間における暴力に関する調査 (令和5年度) ランディング",
        "publisher": "内閣府男女共同参画局",
        "url": "https://www.gender.go.jp/policy/no_violence/e-vaw/chousa/r05_boryoku_cyousa.html",
        "kind": "html",
        "category": "jp",
        "subcategory": "cao",
        "year": 2024,
        "necessity_for": ["product", "research", "policy"],
        "bibtex_type": "misc",
        "notes": "60%/70% 沈黙率の最新版",
    },
    {
        "key": "cao_whitepaper_r4_sexcrime",
        "title": "男女共同参画白書 令和4年版 第1部第5章第2節 性犯罪・性暴力",
        "publisher": "内閣府男女共同参画局",
        "url": "https://www.gender.go.jp/about_danjo/whitepaper/r04/zentai/html/honpen/b1_s05_02.html",
        "kind": "html",
        "category": "jp",
        "subcategory": "cao",
        "year": 2022,
        "necessity_for": ["product", "policy"],
        "bibtex_type": "misc",
        "notes": "「女性6割・男性7割が誰にも相談していない」の公式記述",
    },

    # ========================================================================
    # 🇯🇵 日本 法規
    # ========================================================================
    {
        "key": "law_jp_stalker_regulation",
        "title": "ストーカー行為等の規制等に関する法律 (e-Gov)",
        "publisher": "e-Gov",
        "url": "https://laws.e-gov.go.jp/law/412AC1000000081",
        "kind": "html",
        "category": "laws",
        "subcategory": "jp",
        "year": 2000,
        "necessity_for": ["governance", "product"],
        "bibtex_type": "misc",
    },
    {
        "key": "law_jp_dv_prevention",
        "title": "配偶者からの暴力の防止及び被害者の保護等に関する法律",
        "publisher": "e-Gov",
        "url": "https://laws.e-gov.go.jp/law/413AC1000000031",
        "kind": "html",
        "category": "laws",
        "subcategory": "jp",
        "year": 2001,
        "necessity_for": ["governance"],
        "bibtex_type": "misc",
    },
    {
        "key": "law_jp_pipa",
        "title": "個人情報の保護に関する法律 (個人情報保護法)",
        "publisher": "e-Gov",
        "url": "https://laws.e-gov.go.jp/law/415AC0000000057",
        "kind": "html",
        "category": "laws",
        "subcategory": "jp",
        "year": 2003,
        "necessity_for": ["governance"],
        "bibtex_type": "misc",
        "notes": "27条第三者提供、要配慮個人情報の根拠",
    },
    {
        "key": "law_jp_child_abuse_prevention",
        "title": "児童虐待の防止等に関する法律",
        "publisher": "e-Gov",
        "url": "https://laws.e-gov.go.jp/law/412AC1000000082",
        "kind": "html",
        "category": "laws",
        "subcategory": "jp",
        "year": 2000,
        "necessity_for": ["governance"],
        "bibtex_type": "misc",
    },

    # ========================================================================
    # 🇹🇼 台湾政府統計・報告
    # ========================================================================
    {
        "key": "mohw_dv_landing",
        "title": "家庭暴力防治統計專區 (衛福部保護服務司)",
        "publisher": "衛生福利部保護服務司",
        "url": "https://dep.mohw.gov.tw/DOPS/lp-1303-105-xCat-cat01.html",
        "kind": "html",
        "category": "tw",
        "subcategory": "mohw",
        "year": 2024,
        "necessity_for": ["product", "research", "policy"],
        "bibtex_type": "misc",
        "notes": "親密関係暴力 8.5万件/年の出典",
    },
    {
        "key": "mohw_dv_26th_anniversary",
        "title": "家庭暴力防治法26周年新聞稿",
        "publisher": "衛生福利部",
        "url": "https://www.mohw.gov.tw/cp-2704-79175-1.html",
        "kind": "html",
        "category": "tw",
        "subcategory": "mohw",
        "year": 2024,
        "necessity_for": ["product", "policy"],
        "bibtex_type": "misc",
        "notes": "通報数経年トレンドの公式記述",
    },
    {
        "key": "ey_gender_lgbt_dv",
        "title": "同性親密関係暴力相關統計",
        "publisher": "行政院性別平等會",
        "url": "https://gec.ey.gov.tw/Page/C94CF37B935BEC9/0a15eedd-eb4c-447d-af9b-f02b1a392af4",
        "kind": "html",
        "category": "tw",
        "subcategory": "ey",
        "year": 2024,
        "necessity_for": ["research", "policy"],
        "bibtex_type": "misc",
    },
    {
        "key": "npa_tw_stat_query",
        "title": "警政統計查詢網",
        "publisher": "內政部警政署",
        "url": "https://ba.npa.gov.tw/",
        "kind": "html",
        "category": "tw",
        "subcategory": "npa",
        "year": 2024,
        "necessity_for": ["research"],
        "bibtex_type": "misc",
    },
    {
        "key": "npa_tw_anti_stalking",
        "title": "防制跟蹤騷擾專區",
        "publisher": "內政部警政署",
        "url": "https://www.npa.gov.tw/ch/app/data/list?module=wg203&id=18680",
        "kind": "html",
        "category": "tw",
        "subcategory": "npa",
        "year": 2024,
        "necessity_for": ["product", "policy"],
        "bibtex_type": "misc",
    },

    # ========================================================================
    # 🇹🇼 台湾 法規
    # ========================================================================
    {
        "key": "law_tw_anti_stalking",
        "title": "跟蹤騷擾防制法",
        "publisher": "全國法規資料庫",
        "url": "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=D0080211",
        "kind": "html",
        "category": "laws",
        "subcategory": "tw",
        "year": 2022,
        "necessity_for": ["governance", "product"],
        "bibtex_type": "misc",
    },
    {
        "key": "law_tw_dv_prevention",
        "title": "家庭暴力防治法",
        "publisher": "全國法規資料庫",
        "url": "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=D0050071",
        "kind": "html",
        "category": "laws",
        "subcategory": "tw",
        "year": 1998,
        "necessity_for": ["governance"],
        "bibtex_type": "misc",
    },
    {
        "key": "law_tw_personal_data",
        "title": "個人資料保護法",
        "publisher": "全國法規資料庫",
        "url": "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=I0050021",
        "kind": "html",
        "category": "laws",
        "subcategory": "tw",
        "year": 1995,
        "necessity_for": ["governance"],
        "bibtex_type": "misc",
    },
    {
        "key": "law_tw_sexual_assault_prevention",
        "title": "性侵害犯罪防治法",
        "publisher": "全國法規資料庫",
        "url": "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=D0050108",
        "kind": "html",
        "category": "laws",
        "subcategory": "tw",
        "year": 1997,
        "necessity_for": ["governance"],
        "bibtex_type": "misc",
    },

    # ========================================================================
    # 📚 学術論文 (オープンアクセスのみ直接取得)
    # ========================================================================
    {
        "key": "lisak_miller_2002_landing",
        "title": "Repeat Rape and Multiple Offending Among Undetected Rapists (landing)",
        "publisher": "ResearchGate",
        "url": "https://www.researchgate.net/publication/11379469_Repeat_Rape_and_Multiple_Offending_Among_Undetected_Rapists",
        "kind": "html",
        "category": "academic",
        "subcategory": "underreporting",
        "year": 2002,
        "necessity_for": ["product", "research"],
        "bibtex_type": "article",
        "notes": "Lisak & Miller 4% 仮説の原典。本文は要購読、ランディングのみ保存",
    },
    {
        "key": "nsvrc_rethinking_serial_perpetration",
        "title": "Rethinking Serial Perpetration: Key Findings",
        "publisher": "National Sexual Violence Resource Center",
        "url": "https://www.nsvrc.org/publications/nsvrc-publications-research-briefs/key-findings-rethinking-serial-perpetration",
        "original_url": "https://www.nsvrc.org/sites/default/files/key-findings_rethinking-serial-perpetration.pdf",
        "alternative_url": "https://vawnet.org/material/key-findings-rethinking-serial-perpetration",
        "kind": "html",
        "category": "academic",
        "subcategory": "underreporting",
        "year": 2015,
        "necessity_for": ["product", "research"],
        "bibtex_type": "techreport",
        "notes": "オープンアクセス、4% 仮説のレビュー",
    },
    {
        "key": "callisto_landing",
        "title": "Project Callisto - Ending serial sexual assault",
        "publisher": "Project Callisto",
        "url": "https://www.projectcallisto.org/",
        "kind": "html",
        "category": "academic",
        "subcategory": "callisto",
        "year": 2024,
        "necessity_for": ["product"],
        "bibtex_type": "misc",
        "notes": "FEWN の最強の先行事例",
    },
    {
        "key": "callisto_wikipedia",
        "title": "Callisto (project) - Wikipedia",
        "publisher": "Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Callisto_(project)",
        "kind": "html",
        "category": "academic",
        "subcategory": "callisto",
        "year": 2024,
        "necessity_for": ["product"],
        "bibtex_type": "misc",
    },
    {
        "key": "callisto_2018_landing",
        "title": "Callisto: A Cryptographic Approach to Detecting Serial Perpetrators (landing)",
        "publisher": "ResearchGate (Rajan et al. 2018, ACM COMPASS)",
        "url": "https://www.researchgate.net/publication/325889757_Callisto_A_Cryptographic_Approach_to_Detecting_Serial_Perpetrators_of_Sexual_Misconduct",
        "kind": "html",
        "category": "academic",
        "subcategory": "callisto",
        "year": 2018,
        "necessity_for": ["product"],
        "bibtex_type": "inproceedings",
    },
    {
        "key": "callisto_2026_springer",
        "title": "Callisto: justice for survivors of sexual assault through... (Springer)",
        "publisher": "Journal of Organization Design",
        "url": "https://link.springer.com/article/10.1007/s41469-026-00202-1",
        "kind": "html",
        "category": "academic",
        "subcategory": "callisto",
        "year": 2026,
        "necessity_for": ["product"],
        "bibtex_type": "article",
    },
    {
        "key": "airbox_nature_2022",
        "title": "Translating citizen-generated air quality data into evidence for policy",
        "publisher": "Humanities and Social Sciences Communications (Nature)",
        "url": "https://www.nature.com/articles/s41599-022-01135-2",
        "kind": "html",
        "category": "academic",
        "subcategory": "airbox",
        "year": 2022,
        "necessity_for": ["governance", "policy"],
        "bibtex_type": "article",
        "notes": "オープンアクセス。市民データが政策を動かした学術的根拠",
    },
    {
        "key": "airbox_sinica",
        "title": "AirBox: a participatory PM2.5 sensing system",
        "publisher": "Academia Sinica IIS",
        "url": "https://www.iis.sinica.edu.tw/en/page/report/9828.html",
        "kind": "html",
        "category": "academic",
        "subcategory": "airbox",
        "year": 2017,
        "necessity_for": ["governance"],
        "bibtex_type": "misc",
    },
    {
        "key": "diy_to_dit_2020",
        "title": "From Do-It-Yourself (DIY) to Do-It-Together (DIT)",
        "publisher": "Sustainable Cities and Society (Elsevier)",
        "url": "https://www.sciencedirect.com/science/article/abs/pii/S2210670720308453",
        "kind": "html",
        "category": "academic",
        "subcategory": "airbox",
        "year": 2020,
        "necessity_for": ["governance"],
        "bibtex_type": "article",
        "notes": "ペイウォール、ランディングのみ",
    },
    {
        "key": "ojp_sex_offender_recidivism",
        "title": "Adult Sex Offender Recidivism (Chapter 5)",
        "publisher": "Office of Sex Offender Sentencing, Monitoring, Apprehending, Registering, and Tracking (SMART)",
        "url": "https://smart.ojp.gov/somapi/chapter-5-adult-sex-offender-recidivism",
        "kind": "html",
        "category": "academic",
        "subcategory": "underreporting",
        "year": 2017,
        "necessity_for": ["product", "research"],
        "bibtex_type": "techreport",
        "notes": "Hanson & Morton-Bourgon の引用源",
    },

    # ========================================================================
    # 🌐 国際 NPO・ガイドライン
    # ========================================================================
    {
        "key": "rainn_perpetrator_stats",
        "title": "Statistics: Perpetrators of Sexual Violence",
        "publisher": "RAINN",
        "url": "https://rainn.org/facts-statistics-the-scope-of-the-problem/statistics-perpetrators-of-sexual-violence/",
        "kind": "html",
        "category": "international",
        "subcategory": "rainn",
        "year": 2024,
        "necessity_for": ["product", "research"],
        "bibtex_type": "misc",
    },
    {
        "key": "nnedv_privacy_matters",
        "title": "Why Privacy and Confidentiality Matters for Victims",
        "publisher": "NNEDV (Tech Safety)",
        "url": "https://www.techsafety.org/privacymatters",
        "kind": "html",
        "category": "international",
        "subcategory": "nnedv",
        "year": 2024,
        "necessity_for": ["product", "governance"],
        "bibtex_type": "misc",
    },
    {
        "key": "nnedv_stalking_dv",
        "title": "The Intersections of Stalking and Domestic Violence",
        "publisher": "NNEDV",
        "url": "https://nnedv.org/latest_update/intersections-of-stalking-and-domestic-violence/",
        "kind": "html",
        "category": "international",
        "subcategory": "nnedv",
        "year": 2024,
        "necessity_for": ["product", "research"],
        "bibtex_type": "misc",
        "notes": "ストーカーが殺人リスク3倍に押し上げる根拠",
    },
    {
        "key": "nnedv_camera_guide",
        "title": "A Survivor's Guide to Cameras",
        "publisher": "NNEDV (Tech Safety)",
        "url": "https://www.techsafety.org/guide-to-cameras",
        "kind": "html",
        "category": "international",
        "subcategory": "nnedv",
        "year": 2024,
        "necessity_for": ["product"],
        "bibtex_type": "misc",
    },
]


def by_category(cat: str) -> list[dict]:
    return [r for r in REFS if r["category"] == cat]


def by_necessity(tag: str) -> list[dict]:
    return [r for r in REFS if tag in r.get("necessity_for", [])]


if __name__ == "__main__":
    import json
    print(f"Total refs: {len(REFS)}")
    cats: dict[str, int] = {}
    kinds: dict[str, int] = {}
    for r in REFS:
        cats[r["category"]] = cats.get(r["category"], 0) + 1
        kinds[r["kind"]] = kinds.get(r["kind"], 0) + 1
    print("By category:", json.dumps(cats, indent=2, ensure_ascii=False))
    print("By kind:    ", json.dumps(kinds, indent=2, ensure_ascii=False))
